{% set version = "2.1.0" %}

package:
  name: libastra
  version: {{ version }}

source:
  url: https://github.com/astra-toolbox/astra-toolbox/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7768863a2756887e54829725e8fe95a371c7cb0cdfa5392b2e11cfc290f54dc3
  patches:
    - cmake.patch

build:
  run_exports:
    - {{ pin_subpackage('libastra', max_pin='x.x.x') }}
  ignore_run_exports:
  # conda-build reports the vs2015_runtime is unused
    - vs2015_runtime  # [win]
  number: 2
  string: "{{ "cuda" + cuda_compiler_version|string }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"
  skip: true  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - boost-cpp
    - cudatoolkit
  run:
  # unix uses pthread, but win links to libboost:threads
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}  # [win]
  # astra is written in c++ but seems to prefer including c headers
    - ucrt  # [win]

test:
  requires:
  # libastra uses header-only from Boost, but the unit tests actually link to libboost_unit_test_framework.so
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
  source_files:
    - build/tests/astratest  # [unix]
    - build/tests/astratest.exe  # [win]
  commands:
    - test -f $PREFIX/lib/libastra${SHLIB_EXT}                          # [linux]
    - test -f $PREFIX/lib/libastra${SHLIB_EXT}.0                        # [linux]
    - test -f $PREFIX/lib/libastra${SHLIB_EXT}.0.0.0                    # [linux]
    - "LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH ./build/tests/astratest"  # [unix]
    - if not exist %LIBRARY_LIB%\\AstraCuda64.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\AstraCuda64.dll exit 1  # [win]
    - build\\tests\\astratest                                    # [win]

about:
  home: http://www.astra-toolbox.com
  license: GPL-3.0-only
  license_file:
    - COPYING
    - lib/licenses/rapidxml.txt
  summary: 'libastra is a C++ library of high-performance GPU primitives for 2D
  and 3D tomography.'

extra:
  recipe-maintainers:
    - carterbox
